### PR TITLE
Extend the harvester to collect summary metrics to be displayed by the server.

### LINKED ISSUE #17: Send harvest summary via electronic mail
The harvester should send an electronic mail summarizing its results after each run. This should include at least the fields begin, end, duration, datasets, transmitted, failed for each source and summed over all sources as well as the number of sources considered.

### PR DESCRIPTION
**Pull request by adamreichold**
As a more general alternative to #20.

Closes #17

### CODE REVIEW

File: src/harvester/csw.rs [hunk 1]
```diff
@@ -44,7 +44,7 @@ pub async fn harvest(dir: &Dir, client: &Client, source: &Source) -> Result<()>
         tracing::error!("Failed to harvest {} out of {} datasets", errors, results);
```
Comment (adamreichold) [inline src/harvester/csw.rs]: This logging could move upwards as we return this information now.

**Review by jakobdeller — APPROVED** [review]
